const int HIVE_TYPE_ID_OVERVIEW_VO = 1;
const int HIVE_TYPE_ID_CATEGORY_VO = 2;
const int HIVE_TYPE_ID_BOOK_VO = 3;
const int HIVE_TYPE_ID_BUY_LINKS = 4;
const int HIVE_TYPE_ID_GOOGLE_BOOK_VO=5;
const int HIVE_TYPE_ID_GOOGLE_SEARCH_BOOK_VO=6;
const int HIVE_TYPE_ID_IMAGE_LINKS=7;

const String BOX_NAME_OVERVIEW_VO = "BOX_NAME_OVERVIEW_VO";
const String BOX_NAME_CATEGORY_VO = "BOX_NAME_CATEGORY_VO";
const String BOX_NAME_BOOK_VO = "BOX_NAME_BOOK_VO";
const String BOX_NAME_BOOK_VO_FOR_RECENT = "BOX_NAME_BOOK_VO_FOR_RECENT";
const String BOX_NAME_GOOGLE_SEARCH_VO="BOX_NAME_GOOGLE_SEARCH_VO";